const API_ENDPOINTS = {
  refresh: "/api/user/refresh/",
  sendotp: "/api/user/mobile/send-otp/",
  verifyotp: "/api/user/mobile/verify-otp/",
  onboarding: "/api/user/mobile/onboarding/",
  profile: "/api/user/profile/",
  home_progress: "/api/progress/",
  training_progress: "/api/training/progress/",
  training_puzzles_daily: "/api/training/daily-puzzles/",
  training_goals: "/api/training/goals/",
  challenges: "/api/challenges/",
  past_challenges: "/api/past-challenges/landing/",
  leaderboard: "/api/leaderboard/",
  subjective_submit: "/api/subjective/",
  grid_submit: "/api/grid/",
  chess_submit: "/api/chess/",
  training_subjective_submit: "/api/subjective/",
  training_grid_submit: "/api/grid/",
  training_chess_submit: "/api/chess/",
  feedback: "/api/feedback/",
  home_recommendations: "/api/home/activity-feed/",
  lounge_posts: "/api/lounge-posts/",
  post_create: "/api/lounge-posts/create/",
  all_comments: "/api/comments/",
  search_challenges: "/api/challenges/search/",
  right_section: "/api/home/",
};

const TESTIMONIALS = [
  {
    id: 1,
    text: "Lorem ipsum dolor sit amet consectetur. Vel tincidunt amet rutrum et egestas. Proin ut et posuere fermentum mollis. Vivamus pharetra dignissim pellentesque placerat felis vulputate enim. Risus ut sodales tellus eleifend tincidunt mattis condimentum. Egestas cursus eros venenatis porttitor etiam massa tristique. Vestibulum ipsum.",
    name: "Hellen Jummy",
    role: "Team Lead",
    avatar: "/professional-woman-headshot.png",
  },
  {
    id: 2,
    text: "Lorem ipsum dolor sit amet consectetur. Vel tincidunt amet rutrum et egestas. Proin ut et posuere fermentum mollis. Vivamus pharetra dignissim pellentesque placerat felis vulputate enim. Risus ut sodales tellus eleifend tincidunt mattis condimentum. Egestas cursus eros venenatis porttitor etiam massa tristique. Vestibulum ipsum.",
    name: "Hellen Jummy",
    role: "Team Lead",
    avatar: "/professional-man-glasses.png",
  },
  {
    id: 3,
    text: "Lorem ipsum dolor sit amet consecteturate enim. Risus ut sodales tellus eleifend tincidunt mattis condimentum. Egestas cursus eros venenatis porttitor etiam massa tristique. Vestibulum ipsum.",
    name: "Hellen Jummy",
    role: "Team Lead",
    avatar: "/professional-woman-smiling.png",
  },
  {
    id: 4,
    text: "Lorem ipsum dolor sit amet consectetur. Vel tincidunt amet rutrum et egestas. Proin ut et posuere fermentum mollis. Vivamus pharetra dignissim pellentesque placerat felis vulputate enim. Risus ut sodales tellus eleifend tincidunt mattis condimentum. Egestas cursus eros venenatis porttitor etiam massa tristique. Vestibulum ipsum.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.",
    name: "Hellen Jummy",
    role: "Team Lead",
    avatar: "/professional-man-headshot.png",
  },
  {
    id: 5,
    text: "Lorem ipsum dolor sit amet consectetur. Vel tincidunt amet rutrum et egestas. Proin ut et posuere fermentum mollis. Vivamus pharetra dignissim pellentesque placerat felis vulputate enim. Risus ut sodales tellus eleifend tincidunt mattis condimentum. Egestas cursus eros venenatis porttitor etiam massa tristique. Vestibulum ipsum.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.",
    name: "Hellen Jummy",
    role: "Team Lead",
    avatar: "/professional-man-headshot.png",
  },
  {
    id: 6,
    text: "Lorem ipsum dolor sit amet consectetur. Vel tincidunt amet rutrum et egestas. Proin ut et posuere fermentum mollis. Vivamus pharetra dignissim pellentesque placerat felis vulputate enim. Risus ut sodales tellus eleifend tincidunt mattis condimentum. Egestas cursus eros venenatis porttitor etiam massa tristique. Vestibulum ipsum.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.",
    name: "Hellen Jummy",
    role: "Team Lead",
    avatar: "/professional-man-headshot.png",
  },
  {
    id: 7,
    text: "Lorem ipsum dolor sit amet consectetur. Vel tincidunt amet rutrum et egestas. Proin ut et posuere fermentum mollis. Vivamus pharetra dignissim pellentesque placerat felis vulputate enim. Risus ut sodales tellus eleifend tincidunt mattis condimentum. Egestas cursus eros venenatis porttitor etiam massa tristique. Vestibulum ipsum.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.",
    name: "Hellen Jummy",
    role: "Team Lead",
    avatar: "/professional-man-headshot.png",
  },
  {
    id: 8,
    text: "Lorem ipsum dolor sit amet consectetur. Vel tincidunt amet rutrum et egestas. Proin ut et posuere fermentum mollis. Vivamus pharetra dignissim pellentesque placerat felis vulputate enim. Risus ut sodales tellus eleifend tincidunt mattis condimentum. Egestas cursus eros venenatis porttitor etiam massa tristique. Vestibulum ipsum.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.Lorem ipsum dolor sit amet consectetur.",
    name: "Hellen Jummy",
    role: "Team Lead",
    avatar: "/professional-man-headshot.png",
  },
];

const HEADER_NAV = [
  {
    name: "About Us",
    href: "/about-us",
  },
  {
    name: "Login",
    href: "/login",
  },
];

const GAME_STATS = [
  {
    label: "puzzles solved daily",
    value: "2,500",
  },
  {
    label: "active players",
    value: "125,000",
  },
  {
    label: "User Satisfaction",
    value: "95",
  },
  {
    label: "Days Running",
    value: "1,200",
  },
];

const HOME_NAV = [
  {
    icon: "home",
    text: "Home",
    href: "/home",
  },
  {
    icon: "rank",
    text: "Practice",
    href: "/practice",
  },
  {
    icon: "games",
    text: "Challenges",
    href: "/challenges",
  },
  {
    icon: "person",
    text: "Lounge",
    href: "/lounge",
  },
  {
    icon: "avatar",
    text: "My Profile",
    href: "/myprofile",
  },
];

export const AVAILABLE_JOBPROFILES = [
  "Software Engineer",
  "Data Scientist",
  "Cloud Architect",
  "Cybersecurity Analyst",
  "Network Administrator",
  "UX/UI Designer",
  "Product Manager",
  "Machine Learning Engineer",
  "DevOps Engineer",
  "Full Stack Developer",
  "Database Administrator",
  "IT Support Specialist",
  "AI/ML Researcher",
  "Game Developer",
  "Embedded Systems Engineer",
  "Blockchain Developer",
  "Data Analyst",
  "Business Intelligence Developer",
  "Quality Assurance (QA) Tester",
  "Technical Writer",
  "Scrum Master",
  "Solutions Architect",
  "System Administrator",
  "Front-End Developer",
  "Back-End Developer",
  "Mobile App Developer",
  "Site Reliability Engineer",
  "Network Engineer",
  "Computer Vision Engineer",
  "Robotics Engineer",
  "IoT Engineer",
  "UX Researcher",
  "SEO Specialist",
  "AI Ethicist",
  "Physician",
  "Registered Nurse (RN)",
  "Pharmacist",
  "Physical Therapist",
  "Medical Laboratory Technologist",
  "Dentist",
  "Surgeon",
  "Psychiatrist",
  "Radiologist",
  "Veterinarian",
  "Health Administrator",
  "Occupational Therapist",
  "Nutritionist",
  "Medical Assistant",
  "Nurse Practitioner",
  "Physician Assistant",
  "Physical Therapy Assistant",
  "Dental Hygienist",
  "Optometrist",
  "Chiropractor",
  "Medical Social Worker",
  "Phlebotomist",
  "Paramedic/EMT",
  "Dietitian",
  "Speech-Language Pathologist",
  "Audiologist",
  "Clinical Research Associate",
  "Health Informatics Specialist",
  "Public Health Educator",
  "Genetic Counselor",
  "Financial Analyst",
  "Accountant",
  "Marketing Manager",
  "Human Resources (HR) Manager",
  "Project Manager",
  "Business Analyst",
  "Operations Manager",
  "Sales Representative",
  "Management Consultant",
  "Investment Banker",
  "Auditor",
  "Chief Executive Officer (CEO)",
  "Public Relations (PR) Specialist",
  "Recruiter",
  "Management Analyst",
  "Market Research Analyst",
  "Event Planner",
  "Supply Chain Manager",
  "Logistics Coordinator",
  "Human Resources Generalist",
  "Compensation and Benefits Manager",
  "Financial Planner",
  "Loan Officer",
  "Actuary",
  "Economist",
  "Real Estate Broker",
  "Underwriter",
  "Brand Manager",
  "Account Executive",
  "Graphic Designer",
  "Animator",
  "Content Creator",
  "Architect",
  "Illustrator",
  "Photographer",
  "Filmmaker",
  "Copywriter",
  "Journalist",
  "Music Producer",
  "Fashion Designer",
  "Creative Director",
  "Video Editor",
  "Set Designer",
  "Screenwriter",
  "User Experience (UX) Writer",
  "Content Strategist",
  "Broadcast Journalist",
  "Art Director",
  "Sound Designer",
  "Game Designer",
  "Technical Artist",
  "Exhibition Designer",
  "Costume Designer",
  "Interior Designer",
  "Museum Curator",
  "Urban Planner",
  "Copy Editor",
  "Mechanical Engineer",
  "Civil Engineer",
  "Electrical Engineer",
  "Aerospace Engineer",
  "Chemical Engineer",
  "Industrial Engineer",
  "Environmental Engineer",
  "Biomedical Engineer",
  "Quality Assurance (QA) Engineer",
  "Manufacturing Technician",
  "Automotive Engineer",
  "Materials Engineer",
  "Nuclear Engineer",
  "Petroleum Engineer",
  "Geotechnical Engineer",
  "Architectural Engineer",
  "Marine Engineer",
  "Quality Control Inspector",
  "Production Planner",
  "Industrial Designer",
  "Field Service Technician",
  "CAD Technician",
  "Teacher",
  "Professor",
  "School Counselor",
  "Librarian",
  "Social Worker",
  "School Administrator",
  "Curriculum Developer",
  "Childcare Worker",
  "Psychologist",
  "Career Counselor",
  "Special Education Teacher",
  "Academic Advisor",
  "School Psychologist",
  "Admissions Counselor",
  "Special Education Assistant",
  "Instructional Coordinator",
  "Corporate Trainer",
  "Community Health Worker",
  "Caseworker",
  "Child Life Specialist",
  "Mental Health Counselor",
  "Lawyer/Attorney",
  "Paralegal",
  "Judge",
  "Police Officer",
  "Firefighter",
  "Public Administrator",
  "Politician",
  "Diplomat",
  "Court Reporter",
  "Customs Officer",
  "FBI Agent",
  "Compliance Officer",
  "Intelligence Analyst",
  "Arbitrator",
  "Mediator",
  "Corrections Officer",
  "Legislative Assistant",
  "Electrician",
  "Plumber",
  "Welder",
  "Carpenter",
  "Chef/Cook",
  "Flight Attendant",
  "Real Estate Agent",
  "Personal Trainer",
  "Hairstylist",
  "Automotive Mechanic",
  "HVAC Technician",
  "Landscaper",
  "Automotive Body Repairer",
  "Plasterer",
  "Roofer",
  "Mason",
  "Pest Control Technician",
  "Locksmith",
  "Pastry Chef",
  "Bartender",
  "Personal Shopper",
  "Travel Agent",
  "Hotel Manager",
  "Property Manager",
  "Janitorial Supervisor",
  "Chemist",
  "Biologist",
  "Physicist",
  "Astronomer",
  "Geologist",
  "Ecologist",
  "Forensic Scientist",
  "Meteorologist",
  "Epidemiologist",
  "Research Scientist",
  "Anthropologist",
  "Marine Biologist",
  "Seismologist",
  "Hydrologist",
  "Microbiologist",
  "Survey Researcher",
  "Conservation Scientist",
  "Drone Pilot",
  "Podcaster",
  "YouTuber",
  "Social Media Manager",
  "E-commerce Specialist",
  "Customer Success Manager",
  "Sustainability Consultant",
  "Blockchain Engineer",
  "Chief Diversity Officer",
];

export const LOCATIONS = [
  "Adilabad",
  "Adoni",
  "Agartala",
  "Agra",
  "Ahmedabad",
  "Ahmednagar",
  "Aizawl",
  "Ajmer",
  "Akola",
  "Alappuzha",
  "Aligarh",
  "Alwar",
  "Amaravati",
  "Ambala",
  "Ambikapur",
  "Amravati",
  "Amritsar",
  "Anand",
  "Anantapur",
  "Arrah",
  "Asansol",
  "Aurangabad",
  "Azamgarh",
  "Bagalkot",
  "Balangir",
  "Balasore",
  "Ballari",
  "Bangalore",
  "Banswara",
  "Bareilly",
  "Barmer",
  "Barnala",
  "Barrackpore",
  "Bathinda",
  "Batala",
  "Begusarai",
  "Belagavi",
  "Berhampur",
  "Bettiah",
  "Bhadohi",
  "Bhagalpur",
  "Bharatpur",
  "Bharuch",
  "Bhatpara",
  "Bhavnagar",
  "Bhilai",
  "Bhilwara",
  "Bhimavaram",
  "Bhiwandi",
  "Bhiwani",
  "Bhongir",
  "Bhopal",
  "Bhubaneswar",
  "Bhuj",
  "Bidar",
  "Bikaner",
  "Bilaspur",
  "Bodh Gaya",
  "Bokaro",
  "Botad",
  "Bulandshahr",
  "Burdwan",
  "Burhanpur",
  "Buxar",
  "Chandigarh",
  "Chapra",
  "Chaibasa",
  "Chhatarpur",
  "Chhindwara",
  "Chikkamagaluru",
  "Chittoor",
  "Chitradurga",
  "Cochin",
  "Coimbatore",
  "Cuddalore",
  "Cuttack",
  "Daman",
  "Damoh",
  "Darbhanga",
  "Dausa",
  "Davanagere",
  "Dehradun",
  "Delhi",
  "Deoghar",
  "Dewas",
  "Dhanbad",
  "Dharamshala",
  "Dharmapuri",
  "Dharmavaram",
  "Dhamtari",
  "Dholpur",
  "Dhule",
  "Dhuri",
  "Dibrugarh",
  "Dindigul",
  "Diu",
  "Dimapur",
  "Dumka",
  "Durg",
  "Durgapur",
  "Eluru",
  "Erode",
  "Etah",
  "Etawah",
  "Faizabad",
  "Faridabad",
  "Farrukhabad",
  "Fatehabad",
  "Ferozepur",
  "Firozabad",
  "Gadag",
  "Gandhinagar",
  "Ganganagar",
  "Gangtok",
  "Gaya",
  "Ghaziabad",
  "Giridih",
  "Godhra",
  "Gonda",
  "Gorakhpur",
  "Gudivada",
  "Guna",
  "Guntur",
  "Gurgaon",
  "Guwahati",
  "Gwalior",
  "Hajipur",
  "Haldia",
  "Haldwani",
  "Hanumangarh",
  "Hapur",
  "Haridwar",
  "Hassan",
  "Hazaribagh",
  "Hisar",
  "Hosur",
  "Howrah",
  "Hubli-Dharwad",
  "Hyderabad",
  "Ichalkaranji",
  "Imphal",
  "Indore",
  "Itanagar",
  "Jabalpur",
  "Jagdalpur",
  "Jaipur",
  "Jaisalmer",
  "Jalandhar",
  "Jalgaon",
  "Jalna",
  "Jamalpur",
  "Jammu",
  "Jamshedpur",
  "Jamnagar",
  "Jhansi",
  "Jhalawar",
  "Jhunjhunu",
  "Jind",
  "Jodhpur",
  "Jorhat",
  "Junagadh",
  "Kadapa",
  "Kakinada",
  "Kalaburagi",
  "Kanpur",
  "Kannur",
  "Kanyakumari",
  "Kapurthala",
  "Karaikal",
  "Kargil",
  "Karimnagar",
  "Karnal",
  "Karur",
  "Kasargod",
  "Kasganj",
  "Kashipur",
  "Kasauli",
  "Katihar",
  "Khammam",
  "Khandwa",
  "Kharagpur",
  "Kochi",
  "Kodaikanal",
  "Kohima",
  "Kolhapur",
  "Kolar",
  "Kolkata",
  "Kollam",
  "Koppal",
  "Korba",
  "Kottayam",
  "Kozhikode",
  "Kurukshetra",
  "Kurnool",
  "Latur",
  "Leh",
  "Loni",
  "Lucknow",
  "Ludhiana",
  "Lunglei",
  "Machilipatnam",
  "Madanapalle",
  "Madgaon",
  "Madikeri",
  "Madurai",
  "Mahe",
  "Mahbubnagar",
  "Mahesana",
  "Malappuram",
  "Malerkotla",
  "Manali",
  "Mandi",
  "Mangalore",
  "Mandsaur",
  "Mathura",
  "Medinipur",
  "Meerut",
  "Mirzapur",
  "Moga",
  "Moradabad",
  "Morena",
  "Morbi",
  "Motihari",
  "Munger",
  "Muktsar",
  "Mumbai",
  "Murshidabad",
  "Murwara",
  "Mussoorie",
  "Muzaffarnagar",
  "Muzaffarpur",
  "Mysore",
  "Nadiad",
  "Nagapattinam",
  "Nagaur",
  "Nagercoil",
  "Nagpur",
  "Naharlagun",
  "Nainital",
  "Namakkal",
  "Nanded",
  "Nandyal",
  "Nashik",
  "Navi Mumbai",
  "Navsari",
  "Nellore",
  "Neemuch",
  "New Delhi",
  "Nizamabad",
  "Noida",
  "Ongole",
  "Ooty",
  "Palakkad",
  "Palamu",
  "Pali",
  "Panaji",
  "Panipat",
  "Panvel",
  "Parbhani",
  "Patna",
  "Patiala",
  "Pathankot",
  "Patan",
  "Phagwara",
  "Pilibhit",
  "Pimpri-Chinchwad",
  "Pithoragarh",
  "Porbandar",
  "Port Blair",
  "Pratapgarh",
  "Prayagraj",
  "Proddatur",
  "Puducherry",
  "Pune",
  "Purnia",
  "Puri",
  "Purulia",
  "Raebareli",
  "Raichur",
  "Raiganj",
  "Raipur",
  "Rajahmundry",
  "Rajkot",
  "Rajpura",
  "Rajnandgaon",
  "Ramagundam",
  "Ramgarh",
  "Rampur",
  "Ranchi",
  "Ratlam",
  "Raurkela",
  "Rewa",
  "Rishikesh",
  "Rishra",
  "Rohtak",
  "Roorkee",
  "Rupnagar",
  "Sagar",
  "Saharanpur",
  "Saharsa",
  "Salem",
  "Samastipur",
  "Sambhal",
  "Sambalpur",
  "Sangli",
  "Sangrur",
  "Satara",
  "Satna",
  "Shahjahanpur",
  "Shamli",
  "Shillong",
  "Shimla",
  "Shivamogga",
  "Shivpuri",
  "Siddipet",
  "Silchar",
  "Siliguri",
  "Silvassa",
  "Sikar",
  "Sirsa",
  "Sirohi",
  "Siwan",
  "Sivakasi",
  "Solan",
  "Solapur",
  "Sonipat",
  "Srinagar",
  "Srikakulam",
  "Surat",
  "Surendranagar",
  "Thane",
  "Thanjavur",
  "Theni",
  "Thiruvananthapuram",
  "Thrissur",
  "Tiruchirappalli",
  "Tirunelveli",
  "Tirupati",
  "Tiruppur",
  "Titagarh",
  "Tonk",
  "Tumakuru",
  "Tuticorin",
  "Udaipur",
  "Ujjain",
  "Ulhasnagar",
  "Ulberia",
  "Vadakara",
  "Vadodara",
  "Valsad",
  "Vapi",
  "Varanasi",
  "Vasai-Virar",
  "Vellore",
  "Veraval",
  "Vijayapura",
  "Vijayawada",
  "Villupuram",
  "Visakhapatnam",
  "Vizianagaram",
  "Wardha",
  "Warangal",
  "Yanam",
  "Yamunanagar",
];

export const COUNTRY_CODES = [
  "+93", "+355", "+213", "+1684", "+376", "+244", "+1264", "+672", "+1268",
  "+54", "+374", "+297", "+61", "+43", "+994", "+1242", "+973", "+880", "+1246",
  "+375", "+32", "+501", "+229", "+1441", "+975", "+591", "+387", "+267", "+55",
  "+246", "+1284", "+673", "+359", "+226", "+257", "+855", "+237", "+1", "+238",
  "+1345", "+236", "+235", "+56", "+86", "+57", "+269", "+242", "+243", "+682",
  "+506", "+225", "+385", "+53", "+599", "+357", "+420", "+45", "+253", "+1767",
  "+1809", "+1829", "+1849", "+670", "+593", "+20", "+503", "+240", "+291",
  "+372", "+251", "+500", "+298", "+679", "+358", "+33", "+594", "+689", "+241",
  "+220", "+995", "+49", "+233", "+350", "+30", "+299", "+1473", "+590", "+1671",
  "+502", "+44", "+224", "+245", "+592", "+509", "+504", "+852", "+36", "+354",
  "+91", "+62", "+98", "+964", "+353", "+972", "+39", "+1876", "+81", "+962",
  "+7", "+254", "+686", "+965", "+996", "+856", "+371", "+961", "+266", "+231",
  "+218", "+423", "+370", "+352", "+853", "+389", "+261", "+265", "+60", "+960",
  "+223", "+356", "+692", "+596", "+222", "+230", "+262", "+52", "+691", "+373",
  "+377", "+976", "+382", "+1664", "+212", "+258", "+95", "+264", "+674", "+977",
  "+31", "+687", "+64", "+505", "+227", "+234", "+683", "+850", "+1670", "+47",
  "+968", "+92", "+680", "+970", "+507", "+675", "+595", "+51", "+63", "+870",
  "+48", "+351", "+1787", "+1939", "+974", "+40", "+250", "+290", "+1869",
  "+1758", "+508", "+1784", "+685", "+378", "+239", "+966", "+221", "+381",
  "+248", "+232", "+65", "+1721", "+421", "+386", "+677", "+252", "+27", "+82",
  "+211", "+34", "+94", "+249", "+597", "+268", "+46", "+41", "+963", "+886",
  "+992", "+255", "+66", "+228", "+690", "+676", "+1868", "+216", "+90", "+993",
  "+1649", "+688", "+1340", "+256", "+380", "+971", "+598", "+998", "+678",
  "+379", "+58", "+84", "+681", "+967", "+260", "+263"
];

export const DIFFICULTY_MAP = {
  1: "Easy",
  2: "Easy",
  3: "Medium",
  4: "Hard",
  5: "Hard",
};

export const getDifficultyColor = (difficulty) => {
  switch (difficulty) {
    case "Easy":
      return "bg-blue-100 text-blue-700";
    case "Medium":
      return "bg-orange-100 text-orange-700";
    case "Hard":
      return "bg-red-100 text-red-700";
    default:
      return "bg-gray-100 text-gray-700";
  }
};

export {
  GAME_STATS,
  HEADER_NAV,
  TESTIMONIALS,
  HOME_NAV,
  API_ENDPOINTS,
};
